services:
- docker
# because we're running in a docker
# this is no longer necessary:
# language: python
# python:
# - '3.6'
before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
- docker build -t joshsalvia/webprojectone -f Dockerfile .
script:
- docker run -it joshsalvia/webprojectone python /app/src/manage.py test
deploy:
  provider: script
  script:
    bash ./deploy.sh