services:
- docker
before_install:
- echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- docker-compose -f docker-compose-test.yml up --build --remove-orphans --exit-code-from test_web
deploy:
  provider: heroku
  api_key:
    secure: is3d+XJ99nMCftWtFVslOJR66T7BYGBCmp/rjlK9rrlY/SzphwjQpMoxSFGppXSoXufpVckZLCHO128xVbYIVXIey7YZqg5jNVdPOEDqA7ZsQhHbJFigEXy4vEaKCyTrOGg4sCO/kPlZmJD8M/RlMs8GiYBKZkxxArAc73DhP35D+cokdFoOILyD8kby02/m9bjfdSrdL4XcQ45BBjzlR0UuRR/y0UT48eWdGZ5Tfyw3EwZzoatwIdoNmfUqxFr9yOK7c4xc25o+/Z5LQItAXUmf0eygLvhDEvCZOQKBCeF9hW1HbxoyrJJj0+/ThkJMSHLfzk2rlcgsmOQFzh+HeeHsa+DpuojwsP2SZG89Rxqh6EahixC/SR8JEodwo6xhrsXnrO3JhG6I5/3qhOuixcrsikhgrVWz0KgT6YBJ7GK8Kn9mSrIn+hDun6zkJ5DXRL+1tCJ0yv2pqWx+TeeaWfwiAme/f1LQZshYboeoV/9NHK4qVPH6Ab+7f8+v/9Z+BXuFvS2yYGLPDzkBfhNbn9NoPA8cojmWPXZlRmpLIjdZcQyy3TzcSMvlOkXclRq3C/rwI8NyR7ZUyX91ffyTfPDxxc3sQLz8IV746EDy6skn+xD8V3FYPPNwnSsTbp/7s0PJCDXljvCGQ16mUoIFLyXheXtQXTDtSi8t3/B93EA=
  app: "$HEROKU_APP_NAME"
