version: '3.6'

services:
  web:
    # this is technically not necessary
    # because the Dockerfile already does
    # this if not env is set
    command: /app/start_server_dev.sh
    environment: 
        - PORT=80
    build: ./
    # This is also not necessary because the
    # Dockerfile file itself already copies
    # the content
    # volumes:
    #   - ./:/app/
    ports:
      - 80:80
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: 