version: '3.6'

services:
  web:
    container_name: web_project_server
    restart: on-failure
    # this is technically not necessary
    # because the Dockerfile already does
    # this if not env is set
    command: /app/start_server_dev.sh
    build:
      context: ./
      target: deploy
    # This is used to keep the migrations
    volumes:
      - ./:/app/
    ports:
      - ${WEB_PORT-80}:8080
    env_file:
      - web.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    container_name: web_project_db
    restart: on-failure
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER-hello_django}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-hello_django}
      - POSTGRES_DB=${POSTGRES_DB-hello_django_dev}

volumes:
  postgres_data: 