version: '3.6'

services:
  web:
    container_name: web_project_testing
    restart: on-failure
    # this is technically not necessary
    # because the Dockerfile already does
    # this if not env is set
    command: /app/start_server_dev.sh
    build:
      context: ./
      target: testing
    # This is used to keep the migrations
    volumes:
      - ./:/app/
    ports:
      - ${WEB_PORT-80}:8080
    environment:
      - DEBUG=${DEBUG-1}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS-*}
      - SECRET_KEY=${SECRET_KEY-qu_0pu7t9+nw9amxw+^i#!k+em+k9kmtc5m+h)loo0!%sjiml1}
      - TESTING=1
    stdin_open: true
    tty: true
