version: '3.6'

services:
  web:
    environment: 
        - PORT=80
    build: ./
    command: gunicorn -b 0.0.0.0:80 --chdir /app/src/ webproject.wsgi --log-file -
    # volumes:
    #   - ./:/app/
    ports:
      - 80:80
    