# Generated by Django 3.0.5 on 2020-04-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='bestsellers_date',
        ),
    ]
