# Generated by Django 3.0.5 on 2020-04-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_visualizer', '0002_auto_20200424_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
