# Generated by Django 3.0.5 on 2020-04-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_visualizer', '0003_remove_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
