# Generated by Django 3.0.6 on 2020-05-07 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_visualizer', '0005_auto_20200505_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='whished_by',
        ),
        migrations.AddField(
            model_name='book',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
